### ISSUE TITLE
Permission Error using Pip install

### ISSUE THREAD

**Issue by jkariscodes** [CodeSolid/docker-examples#1]
Encountering an error in the log when installing packages from the requirements.txt file . Here is the screenshot. 
![image](https://user-images.githubusercontent.com/23359514/162687312-c3b50e84-cc52-455c-bd61-d6f7640d78a8.png)

**Comment by ALfuhrmann** [comment]
Had the same error, fixed it [here](https://github.com/ALfuhrmann/docker-examples/pull/1/commits/f16df74c5d5a6b7889f1145e08b3f75ef1944dc3).

You have to change
_RUN useradd myuser_
to
_RUN useradd -m myuser_
in Dockerfile.

**Comment by jkariscodes** [comment]
Thanks. This fixes the issue. It now opens in the browser as shown here. <br>
![image](https://user-images.githubusercontent.com/23359514/163192776-7c9c4baf-611d-4b9f-b966-2b9029972a2e.png)
